import {
  FaGraduationCap,
  FaUniversity,
  FaSchool,
  FaBriefcase,
  FaBookOpen,
  FaCertificate,
  FaMicrochip,
  FaDraftingCompass,
  FaCubes,
  FaServer,
  FaGlobeEurope,
  FaNetworkWired,
  FaCloud,
  FaDatabase,
  FaHdd,
  FaCogs,
  FaShieldAlt,
  FaLanguage,
  FaGlobe,
  FaCalculator,
  FaFlask,
  FaAtom,
  FaBrain,
  FaGithub,
  FaHtml5,
  FaCss3,
  FaJava,
  FaReact,
  FaTools,
  FaGitAlt,
  FaJsSquare,
  FaNodeJs,
} from "react-icons/fa";

import {
  SiReact,
  SiJavascript,
  SiAutodesk,
  SiHtml5,
  SiCss3,
  SiBootstrap,
  SiNextdotjs,
  SiNodedotjs,
  SiMongodb,
  SiTypescript,
  SiTailwindcss,
  SiExpress,
  SiMysql,
  SiArduino,
  SiCplusplus,
  SiServerfault,
  SiLibreofficemath,
  SiWolframmathematica,
  SiAutocad,
} from "react-icons/si";
import { RiEnglishInput } from "react-icons/ri";
import { MdElectricBolt, MdDomain } from "react-icons/md";
import { FcElectronics } from "react-icons/fc";

export const iconMap = {
  FaGraduationCap,
  MdDomain,
  RiEnglishInput,
  FaUniversity,
  FaSchool,
  SiAutodesk,
  FaBriefcase,
  FaBookOpen,
  FcElectronics,
  SiAutocad,
  FaCertificate,
  FaMicrochip,
  FaDraftingCompass,
  FaCubes,
  FaServer,
  FaGlobeEurope,
  FaNetworkWired,
  FaCloud,
  FaDatabase,
  FaHdd,
  FaCogs,
  FaShieldAlt,
  FaLanguage,
  FaGlobe,
  FaCalculator,
  FaFlask,
  FaAtom,
  FaBrain,
  FaGithub,
  FaHtml5,
  FaCss3,
  FaJava,
  FaReact,
  SiReact,
  SiJavascript,
  SiHtml5,
  SiCss3,
  SiBootstrap,
  SiNextdotjs,
  SiNodedotjs,
  SiMongodb,
  SiTypescript,
  SiTailwindcss,
  SiExpress,
  SiMysql,
  SiArduino,
  SiCplusplus,
  SiServerfault,
  SiLibreofficemath,
  SiWolframmathematica,
  MdElectricBolt,
  FaTools,
  FaGitAlt,
  FaJsSquare,
  FaNodeJs,
};

export const categoryColorMap = {
  education: "bg-orange-200",
  internship: "bg-orange-200",
  certificates: "bg-orange-200",
};

export const iconColorMap = {
  HTML5: "text-orange-600",
  CSS3: "text-blue-400",
  JavaScript: "text-yellow-400",
  TypeScript: "text-blue-400",
  React: "text-blue-500",
  "Next.js": "text-white",
  "Tailwind CSS": "text-teal-400",
  Bootstrap: "text-purple-700",
  "Java & OOP": "text-red-500",
  "Node.js": "text-green-500",
  SiExpress: "text-black",
  MongoDB: "text-green-400",
  MySQL: "text-green-400",
  Git: "text-orange-600",
  GitHub: "text-gray-300",
  "VS Code": "text-blue-500",
  "IntelliJ IDEA": "text-purple-500",
  FaReact: "text-cyan-400",
  SiReact: "text-cyan-400",
  SiJavascript: "text-yellow-400",
  SiTypescript: "text-blue-600",
  SiNextdotjs: "text-white",
  SiNodedotjs: "text-green-600",
  FaNodeJs: "text-green-600",
  FaHtml5: "text-orange-600",
  SiHtml5: "text-orange-600",
  FaCss3: "text-blue-500",
  SiCss3: "text-blue-500",
  SiBootstrap: "text-purple-600",
  SiTailwindcss: "text-cyan-500",
  SiExpress: "text-black",
  SiMongodb: "text-green-500",
  SiMysql: "text-blue-600",
  FaDatabase: "text-gray-600",
  FaGithub: "text-black",
  FaGitAlt: "text-orange-600",
  FaCloud: "text-blue-400",
  FaServer: "text-gray-900",
  FaTools: "text-gray-600",
  SiArduino: "text-teal-500",
  SiCplusplus: "text-blue-600",
  FaJava: "text-red-600",
  SiAutocad: "text-red-600",
  SiAutodesk: "text-blue-600",
  SiServerfault: "text-orange-500",
  FcElectronics: "text-blue-500",
  MdElectricBolt: "text-yellow-500",
  FaMicrochip: "text-purple-500",
  FaGlobe: "text-cyan-500",
  FaLanguage: "text-indigo-500",
  RiEnglishInput: "text-blue-600",
  SiLibreofficemath: "text-green-600",
  SiWolframmathematica: "text-red-500",
  FaNetworkWired: "text-indigo-500",
  MdDomain: "text-purple-500",
};

export const getStatusBg = (status) => {
  switch (status) {
    case "completed":
      return "bg-black border-accent";
    case "current":
      return "bg-red-900 border-accent";
    case "upcoming":
      return "bg-yellow-500/20 border-accent";
    default:
      return "bg-gray-500/20 border-accent";
  }
};
